[package]
name = "observer"
version = "0.1.13"
authors = ["AbrarNitk <abrar.nitk@gmail.com>"]
edition = "2018"
description = "Observer"
license = "MIT"
include = ["src/**/*", "Cargo.toml"]
readme = "README.md"
keywords = ["observer", "logging", "events_logging", "function_logging"]
repository = "https://github.com/ackotech/observer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "~1.0.27"
serde_derive = "~1.0.27"
serde_json = "~1.0.9"
failure = "~0.1.1"
uuid = { version = "0.7", features = ["serde", "v4"] }
lazy_static = "~1.3.0"
observer_attribute = "0.1.4"
ackorelic = "~0.1.9"
threadpool = "1.7.1"
diesel = { version = "1.4.3", features = ["postgres", "r2d2", "chrono", "sqlite"] }
r2d2-diesel = "1.0.0"
antidote = "1.0.0"
r2d2 = "0.8"
# ackorelic = {git = "https://github.com/ackotech/ackorelic", branch="query_parse"}
# observer_attribute = {path = "./observer_attribute/"}

[dependencies.chrono]
version = "0.4"
features = ["serde"]

#[dependencies.observer_dqueue]
#path = "./observer_dqueue"
#version = "0.1.0"
#
#[dependencies.observer_queue]
#path = "./observer_queue"
#version = "0.1.0"

[features]
postgres = []
mysql = []
sqlite = []