[package]
name = "observer_attribute"
version = "0.1.0"
authors = ["Amit Upadhyay <code@amitu.com>"]
edition = "2018"

[lib]
proc-macro = true



[dependencies]
quote = "0.6"
proc-macro2 = "0.4"
lazy_static = "~1.2.0"
serde = "~1.0.27"
serde_derive = "~1.0.27"
serde_json = "~1.0.9"

[dependencies.syn]
version = "0.15.34"
features = ["full"]
