[package]
name = "observer_attribute"
version = "0.1.0"
authors = ["Amit Upadhyay <code@amitu.com>"]
edition = "2018"

[lib]
proc-macro = true



[dependencies]
quote = "0.6"
proc-macro2 = "0.4"

[dependencies.syn]
version = "0.15.34"
features = ["full"]
