[package]
name = "balanced_trees"
version = "0.1.0"
authors = ["Amit Upadhyay <code@amitu.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6"


[dependencies.syn]
version = "0.15.33"
features = ["full"]
