[package]
name = "observer_dqueue"
version = "0.1.0"
authors = ["venkatesh <venkatesh@acko.tech>"]
edition = "2018"

[dependencies.observer_queue]
path = "../observer_queue"
version = "0.1.0"

[dependencies]
serde_json = "~1.0.9"